import { StyleSheet, Platform } from 'react-native';
import theme from '../../components/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 30,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    marginBottom: 18,
    paddingHorizontal: 18,
    height: 56,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    shadowColor: 'transparent',
    elevation: 0,
  },
  icon: {
    marginRight: 10,
    opacity: 0.5,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#232D3F',
    backgroundColor: 'transparent',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  selectDisplayText: {
    flex: 1,
    fontSize: 16,
    paddingVertical: Platform.OS === 'ios' ? 17 : 0,
  },
  dropdownIcon: {
    marginLeft: 'auto',
  },
  eyeIcon: {
    paddingLeft: 10,
    opacity: 0.5,
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    marginTop: 2,
    paddingHorizontal: 2,
  },
  switchText: {
    fontSize: 15,
    color: '#232D3F',
  },
  messageContainer: {
    marginBottom: 15,
  },
  button: {
    flexDirection: 'row',
    backgroundColor: '#233D35',
    borderRadius: 16,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
    marginBottom: 18,
    shadowColor: '#B6C7D6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 0.5,
  },
  buttonIcon: {
    marginLeft: 8,
  },
  errorMessage: {
    color: '#E53935',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 8,
  },
  successMessage: {
    color: '#22C55E',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 8,
  },
  footer: {
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 0,
    paddingHorizontal: 8,
  },
  footerAttention: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
    fontWeight: 'bold',
  },
  footerText: {
    fontSize: 12,
    color: '#232D3F',
    textAlign: 'center',
    marginBottom: 3,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '80%',
    maxHeight: '70%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalOption: {
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  modalOptionText: {
    fontSize: 16,
    color: '#333',
  },
  separator: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 5,
  },
  modalCloseButton: {
    marginTop: 20,
    padding: 12,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#555',
  },
});
export default styles;